[profile.default]
src = "src"
out = "out"
libs = ["lib"]
exclude_files = ["script/*"]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
